require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.autodarkmode")
require("core.plugin_config.auto-session")
require("core.plugin_config.lsp")
-- require("core.plugin_config.trim")
require("core.plugin_config.scrolleof")
require("core.plugin_config.formatter")
require("core.plugin_config.mason")
require("core.plugin_config.gitsigns")
require("core.plugin_config.lualine")
